### ISSUE TITLE
[Bug]: What this article helpful input

### ISSUE THREAD

**Issue by solcich** [segmentio/segment-docs#1907]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/destinations/catalog/adobe-analytics/identity/#analyticsjs---device-mode

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

![image](https://user-images.githubusercontent.com/82053428/135112760-bc3db814-284c-4b5b-9778-7eecdc862616.png)

**Comment by markzegarelli** [comment]
Hi @solcich Thanks for providing this feedback. We have a fix that will go out today.

Cheers!
