### ISSUE TITLE
[Content]: GCP Cloud Functions doc doesn't explain request format

### ISSUE THREAD

**Issue by borenstein** [segmentio/segment-docs#1929]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/google-cloud-function/

### What part(s) of the article would you like to see updated?

When writing a GCP cloud function to handle inbound Segment data, I need to know what the body of the request is going to look like so that I can write handlers for it. Without that, I have to find out by trial and error, creating an event that just dumps everything to the console. That's very silly!

**Comment by markzegarelli** [comment]
Hi @borenstein, thanks for submitting this issue. 

Requests to destinations vary widely, depending on the way the Source is configured, and the type of event that is sent.

I think your best bet here will be to use a combination of the Source Debugger, and Destination Event Tester as explained in [Testing Connections](https://segment.com/docs/connections/test-connections/). The Source Debugger, in particular, shows the raw content of the event data received by Segment, which is then sent on to the destination.

I will add this detail to the doc, for future reference.

**Comment by borenstein** [comment]
Great. Yes, clarifying that the request body will be identical to what you
see in the source debugger (if that is true, which it seems to be), would
have saved me a couple hours today.

**Comment by markzegarelli** [comment]
Thanks for confirming, and apologies for the lack of clarity. 

We will add this detail to the doc.
