### ISSUE TITLE
Connection Modes for Autopilot Destination

### ISSUE THREAD

**Issue by jimskeffington** [segmentio/segment-docs#1948]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/autopilothq/

### What part(s) of the article would you like to see updated?

Please include the Connection Modes summary graphic for the Autopilot Destination.  An example of the Braze Connection Modes summary graphic is attached.

![Screen Shot 2021-10-04 at 10 16 34 AM](https://user-images.githubusercontent.com/60675133/135887502-f68f2f6c-4709-4816-a2d7-2f86a46486a8.png)

**Comment by markzegarelli** [comment]
Hi @jimskeffington, It doesn't look like we get the necessary information that we need from the API to infer the connection modes for this destination. We need to have at least one [component](https://github.com/segmentio/segment-docs/blob/b76c021e2c044d87cd9defca58a6a4019c090ce7/src/_data/catalog/destinations.yml#L3335) present for the destination.
