### ISSUE TITLE
[Content]: User.com destination is no longer supported

### ISSUE THREAD

**Issue by fbonawiede** [segmentio/segment-docs#2097]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/user-com/

### What part(s) of the article would you like to see updated?

User.com is not supported anymore

**Comment by markzegarelli** [comment]
Thanks for flagging this, @fbonawiede. I've opened a discussion with our destinations team to figure out if this will work again going forward, or if we will remove the integration and its documentation.

I will leave this ticket open until we have a decision.

**Comment by markzegarelli** [comment]
Hi @fbonawiede, I heard from Segment Support that this issue has been resolved on User.com's side. As a result, I will close this ticket.

If you continue to have issues with this destination, please reach out to [Support](https://app.segment.com/workspaces?contact=1).
