### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by maxKimoby** [segmentio/segment-docs#2198]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/spec/track/

### What part(s) of the article would you like to see updated?

This screenshot should display an example with the common fields as we have no example of how we should spread them in the payload. Are the properties spread in the same object?

![Screen Shot 2021-11-25 at 12 27 55 PM](https://user-images.githubusercontent.com/12074525/143482775-aa35945b-1be4-4a86-a59d-637749b3e154.png)

```rb
# Like that?

analytics.track('My event created', {
  properties: { my_property: 'some_string' },
  context: {},
  #...
})

# Or like that?

analytics.track('My event created', {
  my_property: 'some_string',
  context: {}
})
```

**Comment by markzegarelli** [comment]
Hi @maxKimoby. Apologies for the lengthy delay on this. The Common fields you reference are added automatically by the library you use. You don't need to include those in a Track call. The docs on this are a bit lacking, so we will update them to be more clear.
