### ISSUE TITLE
[Content]: Appcues sending events back into Segment

### ISSUE THREAD

**Issue by Kal-Segment** [segmentio/segment-docs#2235]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/appcues/

### What part(s) of the article would you like to see updated?

https://segment.com/docs/connections/destinations/catalog/appcues/#sending-appcues-events-to-other-segment-partner-services

In this section it explains how to forward Appcues events to 3rd party tools, which is great, however to help clear up some customer confusion it would be useful to explain how those events will flow back into Segment. So after it says:

> _To enable this feature, go to the Integrations Settings in Appcues and click “Activate” under the Segment integration._

it should go on to say "after you have activated the Segment integration, Appcues will automatically forward these events to your workspace, and will appear in the same source debugger.

It's a very small change, however I've had several customers get very confused so the additional clarity would help save time.

**Comment by pwseg** [comment]
@Kal-Segment, we've added this to the page.  Thanks for bringing it to our attention.
