### ISSUE TITLE
Excerpt for Sources Catalog refers to "destinations" instead of "sources"

### ISSUE THREAD

**Issue by alvinslee** [segmentio/segment-docs#2292]
The [Sources Overview](https://segment.com/docs/connections/sources/) page has a "Further reading" section at the bottom which references the "Sources Catalog" and displays the `excerpt` found [here](https://github.com/segmentio/segment-docs/blob/bf7c76be48e407202f7f33a30d2c3a2b258dae60/src/connections/sources/catalog/index.md?plain=1#L6). That `excerpt` is:

> Detailed information about each destination. Learn how our API methods are implemented for that destination.

That looks incorrect to me. Perhaps a more accurate excerpt would be something like:

> A list of the available sources on the Segment platform.

**Comment by forstisabella** [comment]
Addressed in PR #2311
