### ISSUE TITLE
[Content]: Doesn't explain why NPM isn't an option

### ISSUE THREAD

**Issue by matthew-dean** [segmentio/segment-docs#2293]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/

### What part(s) of the article would you like to see updated?

Most web developers would expect to see a Yarn / NPM command to install a library and include that in something like a Webpack vendor bundle. However, Segment seems to use a very old-style method of copy / pasting something into the `<head>` tag.

If, for some reason, this is necessary, this article needs to explain why. Otherwise web devs will seek out some one else's hack for installing via NPM. If this method is simply legacy, then Segment should publish an NPM-installable library.

**Comment by markzegarelli** [comment]
Hi @matthew-dean, thanks for letting us know about this trouble spot. We should absolutely document that installation through Yarn / [NPM](https://www.npmjs.com/package/@segment/snippet) are available.

We have instructions on that [here](https://github.com/segmentio/analytics-next#-using-as-an-npm-package), which we'll add to the docs site as well.
