### ISSUE TITLE
[Content]: CleverTap supports Cloud Mode as well

### ISSUE THREAD

**Issue by shahharsh093** [segmentio/segment-docs#2303]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/clevertap/

### What part(s) of the article would you like to see updated?

1. 

In CleverTap Destination [document](https://segment.com/docs/connections/destinations/catalog/clevertap/), under "Connection modes", the table states that only Device-mode Web, Mobile are supported, which is inaccurate.

CleverTap Destination actually supports : 
Device-mode: Web, Mobile
Cloud-mode : Web, Mobile, Server

2. 

Similar to #1, update the same information under "[Supported Sources and Connection Modes](https://segment.com/docs/connections/destinations/catalog/clevertap/#supported-sources-and-connection-modes
)"

**Comment by markzegarelli** [comment]
Hi @shahharsh093, thanks for letting us know about this.

The reason the CleverTap connection modes display the way they are is this:

For our documentation, we infer integration connection modes using the Supported Platforms, and available Components. In CleverTap's case, we see that they do support Browser, Mobile, and Server components. However, there are no available Server or Cloud components (Only [Browser](https://github.com/segment-integrations/analytics.js-integration-clevertap), [iOS](https://github.com/CleverTap/clevertap-segment-ios), and [Android](https://github.com/CleverTap/clevertap-segment-android)).

This means that our process that computes connection modes does not see any cloud connections available.

I'll do some digging on my side to see if there is a workaround for this, or I will manually override the connection modes to update. This issue will remain open in the mean time.

**Comment by shahharsh093** [comment]
Thanks, @markzegarelli for looking into this. Possible to manually override the connection modes so that the documentation reflects the connection mode state accurately.

Looking forward to your responsne.
