### ISSUE TITLE
[Content]: Appcues destination accepts Track and Group calls

### ISSUE THREAD

**Issue by jmuething** [segmentio/segment-docs#2314]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/appcues/

### What part(s) of the article would you like to see updated?

The Appcues destination has support Track calls for a long time, and has just added Group support as well.

I am planning on submitting a PR to add a section in the main body of the doc for Group (a Track section already exists), but I'd also like Track and Group reflected in the "Destination Info" up top:
![Appcues Destination Segment Documentation 2022-01-07 at 9 45 27 AM](https://user-images.githubusercontent.com/14317837/148568717-0b2e49ff-6a5f-482f-a7d8-9b0a3cb81aeb.jpg)

### Additional information

This is the new Group section in the body of the doc (after "Identify" and before "Track") I was planning on submitting as a PR to update, but let me know if it can just be included along with this Issue :

## Group

Refer to the Segment Spec for information about the [Group method](/docs/connections/spec/group/). The following represents an example `group` call:

```javascript
analytics.group("0e8c78ea9d97a7b8185e8632", {
  name: "Initech",
  industry: "Technology",
  employees: 329,
  plan: "enterprise",
  "total billed": 830
});
```

When you call `group` with Analytics.js, Segment calls `Appcues.group`. This is the preferred method of using and targeting on account-level properties.

**Comment by markzegarelli** [comment]
Hi @jmuething. Thanks for letting us know about this issue!

The information in the top section of the docs that you highlighted in your screenshot is pulled from our Public API, which itself pulls information from the destination's configuration.

The list of accepted calls that we get in the API return is:

```
"supportedMethods": {
    "track": false,
    "pageview": true,
    "identify": true,
    "group": false,
    "alias": false
},
```

You may want to reach out to Segment Customer Success directly to ensure that this is accurately reflected in the destination config.  Once added there, we'll happily take a PR to update the content.
