### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by BillyOwenSegment** [segmentio/segment-docs#2319]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/clevertap

### What part(s) of the article would you like to see updated?

Hi Team,

Can we please clarify whether server-side is supported here as no green tick on the page?
https://segment.com/docs/connections/destinations/catalog/clevertap/#supported-sources-and-connection-modes

Thanks!

**Comment by markzegarelli** [comment]
#2303
