### ISSUE TITLE
[Bug]: Identify Example Uses Wrong Arguments

### ISSUE THREAD

**Issue by seekayel** [segmentio/segment-docs#2327]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/spec/identify/

### Please describe the issue.

Calling identify as shown in the example throws an error. You need to wrap in an object.

**Docs: (wrong)**
```js
analytics.identify("97980cfea0067", {
  name: "Peter Gibbons",
  email: "peter@example.com",
  plan: "premium",
  logins: 5
});
```

**Corrected**
```js
analytics.identify({
  userId: "97980cfea0067",
  traits: {
    name: "Peter Gibbons",
    email: "peter@example.com",
    plan: "premium",
    logins: 5
  }
});
```

**ERROR**
(node:27415) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: You must pass a message object.

**Others having trouble:**
https://github.com/segmentio/analytics-node/issues/192

**Comment by rchinn-segment** [comment]
Hi @seekayel, thanks for contributing. 
This correction is specific to NodeJS library. We have a separate page on NodeJS that uses this syntax: https://segment.com/docs/connections/sources/catalog/libraries/server/node/

**Comment by seekayel** [comment]
@rchinn-segment thanks for the link. That page looks good.

At least for me I would expect the browser API and the server side API to be the same. I'm assuming the main docs are only showing the browser javascript api? Seems a bit confusing.

**Comment by rchinn-segment** [comment]
Hi @seekayel, We'll add a note to the documentation, along with a link to the Node.js doc, and point this discrepancy out to the engineering team. Thanks for bringing this to our attention.
