### ISSUE TITLE
Device Modes 

### ISSUE THREAD

**Issue by BillyOwenSegment** [segmentio/segment-docs#2342]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/doubleclick-floodlight/

### What part(s) of the article would you like to see updated?

As per [this ticket](https://segment.zendesk.com/agent/tickets/432696) it appears cloud mode is not available for web:

Yes, I am afraid that device mode is required for these settings to function. In fact, this destination is actually required to operate in device mode when connected to a web source. Cloud mode is only supported when DoubleClick Floodlight is connected to a mobile source or a server source. If cloud mode was supported for a web source there would be a connection mode setting that would allow you to toggle between device mode and cloud mode. If you are unable to use analytics.js with device mode destinations then the Doubleclick Floodlight destination may not be an option. 

Can we please clarify what modes are available in the docs?

**Comment by markzegarelli** [comment]
Thanks for submitting this @BillyOwenSegment. Connection modes for destinations are calculated automatically, so I will add an override for this destination.
