### ISSUE TITLE
[Content]: Missing information on Swift Package Manager support

### ISSUE THREAD

**Issue by jfrodden** [segmentio/segment-docs#2377]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/quickstart/

### What part(s) of the article would you like to see updated?

The article promotes CocoaPods as preferred method of import and does not mention your Swift Package Manager support.

**Comment by stayseesong** [comment]
@jfrodden Thanks for submitting this issue! I created a PR to address the fix [here](https://github.com/segmentio/segment-docs/pull/2391) if you'd like to take a look and see if this fixes the issue.
