### ISSUE TITLE
[Content]: Computed Traits - additional description

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#2401]
### What article on segment.com/docs is affected?

https://segment.com/docs/personas/computed-traits/

### What part(s) of the article would you like to see updated?

Currently the information around computed traits isn't that clear and could be improved by providing information that's found in [Intercom's docs](https://segment.com/docs/connections/destinations/catalog/intercom/#:~:text=User%2DLevel%20Traits,the%20last%20sync.) 

The primary aspect to be updated and made clearer for customer is what is sent/included in the track/identify calls for traits, this being the property and value not the original event or entire user profile.

**Comment by markzegarelli** [comment]
@rchinn-segment Can you take a look at this when you have a few minutes?

**Comment by rchinn-segment** [comment]
Hi @lizkane222, I’ve created a PR to address this issue and provide a bit more information on computed traits. You can see a preview [here](https://deploy-preview-2415--segment-docs.netlify.app/docs/personas/computed-traits/#connecting-your-computed-trait-to-a-destination). Thanks for bringing this to our attention!
