### ISSUE TITLE
[Content]: Add content for how to use arrays in Personas

### ISSUE THREAD

**Issue by mmcspiritt** [segmentio/segment-docs#2439]
### What article on segment.com/docs is affected?

https://segment.com/docs/personas/faqs/

### What part(s) of the article would you like to see updated?

Add Q/A for how to use Arrays in Personas Audiences/Traits. Should outline examples for how it has been used // how it can be used.

**Comment by markzegarelli** [comment]
@pwseg Can you take a look at this one to see if we can squeeze something in this quarter?

**Comment by pwseg** [comment]
@mmcspiritt It looks like Personas doesn't support arrays, so I'm going to close this one out.  I'll keep an eye on this, though, in case we need to update it in the future.
