### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by HerrNiklasRaab** [segmentio/segment-docs#2512]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/destinations/catalog/firebase/#:~:text=this%20documentation%20from%20Firebase%20to%20set%20up%20your%20conversions%20in%20Firebase%20and%20to%20have%20them%20forwarded%20to%20Adwords.

### Please describe the issue.

Click the link to see where: https://segment.com/docs/connections/destinations/catalog/firebase/#:~:text=this%20documentation%20from%20Firebase%20to%20set%20up%20your%20conversions%20in%20Firebase%20and%20to%20have%20them%20forwarded%20to%20Adwords.

**Comment by markzegarelli** [comment]
Thanks @HerrNiklasRaab! We don't know where Google has moved this content to, so unfortunately we'll need to remove the link entirely.
