### ISSUE TITLE
[Content]: SendGrid Personas Caveat 

### ISSUE THREAD

**Issue by k-griese** [segmentio/segment-docs#2549]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/sendgrid/

### What part(s) of the article would you like to see updated?

Some clients have been asking to use SendGrid Source data in Personas. It is my understanding that this is not possible today. Can we add a disclaimer to notify users that using SendGrid data is not available in Personas? Ideally, we would like to eventually add instruction that would enable users to use their SendGrid data in Personas but until then, we may need to caution users.

**Comment by pwseg** [comment]
@k-griese We've added a note about this to the SendGrid page.  Thanks for bringing it to our attention.
