### ISSUE TITLE
[Content]: Move CleverTap from Analytics to CRM

### ISSUE THREAD

**Issue by shahharsh093** [segmentio/segment-docs#2551]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/clevertap/

### What part(s) of the article would you like to see updated?

Request here is to move the CleverTap destination document from Analytics to CRM. More of our mutual customers use ClevereTap as a CRM today as compared to Analytics. 

Having CleverTap listed under CRM will help users find the documentation faster.

### Additional information

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/5040880/156420719-1a976940-27bb-4ded-a625-8a7e8ffffe4e.png">

**Comment by markzegarelli** [comment]
Hi @shahharsh093. [Segment support](https://app.segment.com/workspaces?contact=1) can help change categories for CleverTap. Our docs info is populated from a system of record, that controls metadata in the Segment App as well.
