### ISSUE TITLE
[Content]: Klaviyo server side track properties mapping is missing

### ISSUE THREAD

**Issue by mikey555** [segmentio/segment-docs#2588]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/klaviyo/#server-side-track

### What part(s) of the article would you like to see updated?

It looks like it's missing the properties after the line:
`We will also map the following Segment spec’d properties to Klaviyo’s [special people properties](http://www.klaviyo.com/docs):`

### Additional information

![Screen Shot 2022-03-09 at 4 55 18 PM](https://user-images.githubusercontent.com/983004/157565560-b9dfee6f-b652-42a7-a368-8de3a06c8fa0.png)

**Comment by forstisabella** [comment]
Closing this one, as Segment is deprecating the Klaviyo destination at the end of the month.
