### ISSUE TITLE
[Content]: Create a Data Extension in SFMC for each Track event

### ISSUE THREAD

**Issue by Gavin-Fitzpatrick** [segmentio/segment-docs#2605]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/salesforce-marketing-cloud/#set-up-to-send-track-calls-to-sfmc

### What part(s) of the article would you like to see updated?

Currently the line highlighted [here](https://segment.com/docs/connections/destinations/catalog/salesforce-marketing-cloud/#:~:text=SFMC%20destination%20in%20Segment.-,The%20example%20below%20shows%20a%20Data%20Extension%20for,properties%3A,-Configure%20the%20SFMC%20Destination) can be misleading as it can be interpreted that the automatically added timestamp values will be sent by segment to Salesforce. However, in practice this value is not passed and would have to added as a property in the track call itself to be sent to the destination. A warning to indicate that timestamps are not sent automatically by Segment could reduce the confusion with this subject.

**Comment by markzegarelli** [comment]
@stayseesong can you take a look at this one when you have a chance?

**Comment by stayseesong** [comment]
@Gavin-Fitzpatrick here's a [preview link ](https://deploy-preview-2673--segment-docs.netlify.app/docs/connections/destinations/catalog/salesforce-marketing-cloud/#set-up-to-send-track-calls-to-sfmc) of the fix with the warning label added in. Would you like any changes to it? 

I created a [PR](https://github.com/segmentio/segment-docs/pull/2673) to address the issue.
