### ISSUE TITLE
[Content]: Remove `default_app_config` suggestion for django docs

### ISSUE THREAD

**Issue by nbhargava** [segmentio/segment-docs#2688]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/server/python/#django

### What part(s) of the article would you like to see updated?

This part of the article suggests that we should set `default_app_config`, but this feature will be removed in Django 4.1, and yields the following warning when included:
```
/usr/local/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'myapp' defines default_app_config = 'myapp.apps.MyAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

**Comment by markzegarelli** [comment]
@stayseesong, can you please check with the Libraries team to gauge the impact of this?

**Comment by stayseesong** [comment]
closing the issue out as the libraries team did not have an opinion
