### ISSUE TITLE
Broken Link to Adobe Documentation[Bug]: 

### ISSUE THREAD

**Issue by k-griese** [segmentio/segment-docs#2751]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/destinations/catalog/adobe-analytics/

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

The hyperlink used for further context on "[Context Data Variables](https://marketing.adobe.com/resources/help/en_US/sc/implement/context_data_variables.html)" goes to a _page not found_ page.

Link used: https://marketing.adobe.com/resources/help/en_US/sc/implement/context_data_variables.html

**Comment by pwseg** [comment]
@k-griese Thanks for spotting this.  I've fixed these links in our docs, though it may take a few days for the page to reflect the changes.
