### ISSUE TITLE
[Content]: Klaviyo Personas Section

### ISSUE THREAD

**Issue by seanhan-segment** [segmentio/segment-docs#2755]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/klaviyo/#personas

### What part(s) of the article would you like to see updated?

The existing Personas content for the Klaviyo destination doc does a nice job explaining our standard-ish practice of sending identify() calls downstream, which update user profiles in Klaviyo. But it's missing two things that I think make things misleading for users:

1. The following is _implied_ but I think should be explicitly stated at the end of the Personas section: "Once Segment's identify() call sets a custom property on the Klaviyo user profile for a Personas audience, Klaviyo segments can be created off that property when its value is "true". This will ensure membership is updated automatically as users fall in and out of eligibility criteria for the Personas audience". 
2. In the Segment UI, a user is prompted to enter a list_id as an optional field. If that's filled in, our [Klaviyo destination code](https://github.com/segmentio/integrations/blob/24fd18d9fe74a47512558172614be71be8b29fd7/integrations/klaviyo/lib/index.js#L63) will fire its _addToList method instead of the normal identify() approach. _addToList, from what I can tell, only ADDS users to the provided list_id. It does not provide a way to REMOVE users. So by including a list_id in the destination settings, it breaks the expectation set by the existing Personas language (which implies Personas will automatically keep the membership up to date). So in tandem with (1) above, I think the writeup should include a warning box for Personas along the lines of "inputting a list id in the destination settings is not recommended for Personas destinations. Doing so will instruct Segment to add users to the provided list_id, but users will not be removed. Instead leave list id empty and see guidance above for creating Klaviyo segments" (and reference (1)).

**Comment by pwseg** [comment]
@seanhan-segment We've updated the [Klaviyo Personas section](https://segment.com/docs/connections/destinations/catalog/klaviyo/#personas) with this content.  Thanks for bringing it to our attention.
