### ISSUE TITLE
[Content]: SMS Send should be SMS Delivered

### ISSUE THREAD

**Issue by cannyeo** [segmentio/segment-docs#2791]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/iterable/

### What part(s) of the article would you like to see updated?

Under the Collection table: https://segment.com/docs/connections/sources/catalog/cloud-apps/iterable/#collections

I noticed the actual event parsed for SMS Send is SMS Delivered.

**Comment by markzegarelli** [comment]
@stayseesong Can you take a look at this one as well when you have a moment?

**Comment by stayseesong** [comment]
hi @cannyeo, sorry for addressing this issue so late! But wanted to clarify, what's the issue you found? Should SMS Delivered be SMS Send instead?

**Comment by cannyeo** [comment]
hi @stayseesong :) ,we wondered about that too. Here's a [screenshot](https://ibb.co/Q8TtswZ) of Iterable source Schema on Segment that shows SMS related events.

**Comment by stayseesong** [comment]
It looks like SMS Delivered is correct
