### ISSUE TITLE
[Content]: Missing Analytics Rust doc

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#2810]
### What article on segment.com/docs is affected?

Analytics-rust

### What part(s) of the article would you like to see updated?

There is no documentation for analytics-rust even though the [github](https://github.com/segmentio/analytics-rust) points to our docs twice.
- https://segment.com/docs/connections/sources/#server
- https://segment.com/docs/libraries/rust/

**Comment by markzegarelli** [comment]
@stayseesong Can you check with the libraries team to see if there is any plan for these libraries? We have documentation for Rust, but it's hidden and unpublished.

We should either update and make public, or remove the link from the GitHub repo.

**Comment by stayseesong** [comment]
@markzegarelli the team said Rust is not officially supported, and while the library exists, it's not actively maintained. I got the ok to just remove the links from the repo. I removed https://segment.com/docs/libraries/rust/ and submitted a [PR](https://github.com/segmentio/analytics-rust/pull/10) to update the readme to remove the other docs link

**Comment by markzegarelli** [comment]
Sweet, thanks for the quick turnaround @stayseesong. I will close this one out.
