### ISSUE TITLE
[Content]: iOS Swift and Objective C examples switched

### ISSUE THREAD

**Issue by ashton-huxtable** [segmentio/segment-docs#2825]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#disabling-data-collection-for-users-who-opt-out

### What part(s) of the article would you like to see updated?

The examples for Swift and Objective C under the **'Disabling Data Collection for Users who opt out'** section are switched. See screenshots below. 
![Screen Shot 2022-05-02 at 12 07 41 PM](https://user-images.githubusercontent.com/78318468/166302282-2e58b443-5802-459b-83c9-628aacde275a.png)

![Screen Shot 2022-05-02 at 12 07 48 PM](https://user-images.githubusercontent.com/78318468/166302298-58f2a345-d124-4dc4-9951-503db2089ee4.png)

**Comment by markzegarelli** [comment]
@stayseesong, this should be a relatively quick fix.
