### ISSUE TITLE
[Bug]: Duplicated properties and descriptions for trackForm

### ISSUE THREAD

**Issue by jessehalpern** [segmentio/segment-docs#2856]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#track-form

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

Copy/paste issue

**Comment by pwseg** [comment]
@jessehalpern We've fixed this.  Thanks so much for bringing it to our attention.
