### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by k-griese** [segmentio/segment-docs#2859]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/snowflake/

### What part(s) of the article would you like to see updated?

It seems like the Snowflake Source documentation has been removed. Can we please have this page updated with current documentation?

### Additional information

![Screen Shot 2022-05-09 at 10 28 58 AM](https://user-images.githubusercontent.com/92601950/167432222-0d4e2643-7212-4ccc-8a10-1f5a757559e5.png)

**Comment by markzegarelli** [comment]
Hi @k-griese, this page was erroneously exposed. We do not have a Snowflake source at this time. However, we do have a [destination](https://segment.com/docs/connections/storage/catalog/snowflake/) that can help you get data _in_ to Snowflake.

We'll hide the Snowflake Source page to eliminate confusion going forward.
