### ISSUE TITLE
[Content]: Clarify 24h deduplication window on "Handling Duplicate Data" page

### ISSUE THREAD

**Issue by seanhan-segment** [segmentio/segment-docs#2885]
### What article on segment.com/docs is affected?

https://segment.com/docs/guides/duplicate-data/#99-deduplication

### What part(s) of the article would you like to see updated?

The references to 24h in the following sections make it sound like we strictly enforce a 24h dedupe window. But the window is actually more than 24h per this thread with Albert Strasheim: https://segment.slack.com/archives/C3M0DBHS6/p1650647809447239

To make the following a bit more accurate/less confusing, the suggestion from the slack thread is instead of saying "within 24 hours" to say "within at least 24 hours". 

_Segment guarantees that 99% of your data won’t have duplicates within a 24 hour look-back window. Warehouses and Data Lakes also have their own secondary deduplication process to ensure you store clean data.

99% deduplication
Segment has a special deduplication service that sits behind the api.segment.com endpoint and attempts to drop 99% of duplicate data. Segment stores 24 hours worth of event message_ids, allowing Segment to deduplicate any data that appears within a 24 hour rolling window.

Segment deduplicates on the event’s message_id, not on the contents of the event payload. Segment doesn’t have a built-in way to deduplicate data over periods longer than 24 hours or for events that don’t generate message_ids._

**Comment by forstisabella** [comment]
Hi @seanhan-segment: I'm taking a look at this and have a question about the intended timeframe of the deduplication! The Slack thread was lost to the migration, but if Segment deduplicates over 24+ hours, what timeframe would make sense in the context of this sentence? _"Segment doesn’t have a built-in way to deduplicate data over periods longer than __24 hours__ or for events that don’t generate message_ids."_ Would 48 hours be the right timeframe, or could I take the "over periods longer than 24 hours" out of that sentence?
