### ISSUE TITLE
[Content]: Update snippet to include category value

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#2906]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/google-analytics/#:~:text=Virtual%20Pageviews,com/%27%0A%7D)%3B

### What part(s) of the article would you like to see updated?

The codeblock should include the **_name_** and **_category_** corresponding to the **_title_** as it could mislead customers into thinking they don't need to include these fields. When no name or category is sent with the page event, the event in GA has no name.

> `analytics.page('Form', 'Signup Modal', {
  title: 'Signup Modal',
  url: 'https://segment.com/#signup',
  path: '/#signup',
  referrer: 'https://segment.com/'
});`

It may also be beneficial to include a screenshot of this resulting event in GA.

**Comment by markzegarelli** [comment]
@lizkane222 Does this code block have the necessary information?

```
analytics.page({
    category: "Acqusition",
    name: "Signup",
    properties: {
        title: 'Signup Modal',
        url: 'https://segment.com/#signup',
        path: '/#signup',
        referrer: 'https://segment.com/'
    }
});
```

**Comment by lizkane222** [comment]
Hey Mark, 

If this event is sent from the client like this : `analytics.page("Acqusition", "Signup");`  
OR if the full event is sent like below (same thing)
```
analytics.page('Acqusition', 'Signup', {
  category: 'Acqusition',
  name: 'Signup',
  path: '/signup',
  referrer: '',
  search: '',
  title: 'Acqusition | Signup',
  url: 'http://localhost:4000/signup'
});
```

**The result in Segment is this :** 
```
analytics.page('Acqusition', 'Signup', {
  category: 'Acqusition',
  name: 'Signup',
  path: '/signup',
  referrer: '',
  search: '',
  title: 'Acqusition | Signup',
  url: 'http://localhost:4000/signup'
});
```

**The result in Google Analytics is this :** 
![Google Analytics - Page Title = concatenated Category   Name](https://user-images.githubusercontent.com/68755692/171526199-845fe3ce-75f3-45e5-bbb9-0dfd9663dde0.png)

Feel free to use the image I provided above in the docs, as there isn't any workspace-specific data referenced in the screenshot.
