### ISSUE TITLE
[Content]: Create AWS Glue ETL Job

### ISSUE THREAD

**Issue by HusseinWarsame** [segmentio/segment-docs#2949]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/amazon-personalize/

### What part(s) of the article would you like to see updated?

In Step 10 of Create AWS Glue ETL Job, there is source code for transforming Segment Events from JSON to CSV. 

In line 21 of the source code, we have

`datasource0 = glueContext.create_dynamic_frame.from_options('s3', {'paths': [args['S3_JSON_INPUT_PATH']]}, 'json')`

but that line will not create a dynamic frame with records. It will only look at the immediate input path, segment-logs/, and fail to create any records.

I propose changing it to: 
`datasource0 = glueContext.create_dynamic_frame.from_options('s3', {'paths': [args['S3_JSON_INPUT_PATH']], 'recurse': True}, 'json')`

The addition of `'recurse: True'` is needed to read all data from child folders of segment-logs.

**Comment by forstisabella** [comment]
> @forstisabella Can you take a look at this one when you have a moment?

Sure can! I'll take a look this afternoon.
