### ISSUE TITLE
[Content]: Schema Event Filters disable button

### ISSUE THREAD

**Issue by ashton-huxtable** [segmentio/segment-docs#3018]
### What article on segment.com/docs is affected?

https://segment.com/docs/protocols/schema/#event-filters

### What part(s) of the article would you like to see updated?

The section provides a preview of event filters that allow for the customer to disable the event for all destinations. When a source is connected to a Protocols tracking plan, however, this option does not exist:
<img width="1218" alt="Screen Shot 2022-06-09 at 3 13 56 PM" src="https://user-images.githubusercontent.com/78318468/173097354-97c0fda8-6522-452e-8a2a-21506ae8579a.png">

Because this section of the docs falls within the Protocols docs, the example should reflect what customers will see in the UI. It should be noted they can turn off the event for individual destinations, but not all at once when connected to a tracking plan. The intention is that they are using a tracking plan and planning for these events. They would be able to block unplanned events easily with Protocols. 

This has caused some confusion for customers who are expecting to be able to toggle the event off for all destinations.

**Comment by markzegarelli** [comment]
Thanks @ashton-huxtable! We'll add a note to this section of the doc that explains the impact that a connected tracking plan has on this tool.
