### ISSUE TITLE
[Content]: Spec: Common Field #Integrations

### ISSUE THREAD

**Issue by 1337Lurker** [segmentio/segment-docs#3033]
### What article on segment.com/docs is affected?

Spec: Common Fields

### What part(s) of the article would you like to see updated?

The questions I have remaining after reading the `Integrations` section

* What is the significance of the key?
  * Can you specify a specific instance of a Destination? e.g. `Mixpanel - This One` so that `Mixpanel - Not This One` does not receive the event?
  * Is it each Destination type? (Mixpanel, Salesforce)
* Where can I find an enumerated list of the Destinations?

**Comment by markzegarelli** [comment]
Hi @1337Lurker, thanks for the question.

It appears that it's not possible to target individual instances of a destination from the integrations object. I will update the documentation on the Common spec page to reflect this. So if you have multiple instances of Mixpanel, options you apply to `Mixpanel` in the Integrations object will apply to all of those instances.

As for your second question, can you expand a bit on what you're looking for in an enumerated list of destinations?

**Comment by 1337Lurker** [comment]
For a given destination, how do I specify the Integration key? The example includes "Salesforce", but it's not enough context to know if the integration key is only the name given in the Catalog, or if it's PascalCase. I could be overthinking it, but clarity would be appreciated.

Example: Which is the correct Facebook Pixel key to specify?
```json
{
	[...]
	"Integrations": {
		"Facebook Pixel": true,
		"FacebookPixel": true
		"Facebook_Pixel": true
	}
}
```

**Comment by markzegarelli** [comment]
Each destination's documentation page has this information at the top. 

For example, in the Facebook Pixel [article](https://segment.com/docs/connections/destinations/catalog/facebook-pixel/#:~:text=Referred%20to%20as,Integrations%20object), there is a bullet in the Destination Info that displays the name you should use in the integration object.
