### ISSUE TITLE
[Content]: Update HTTP to HTTPS

### ISSUE THREAD

**Issue by atitsh** [segmentio/segment-docs#3042]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/functions/source-functions/

### What part(s) of the article would you like to see updated?

Update the source functions document to say HTTPS instead of HTTP. 

For example, section "Code the source function", 
statement "This function is executed by Segment for each HTTP request sent to this function’s webhook."

**Comment by pwseg** [comment]
@atitsh Thanks for bringing this to our attention.  We've made these changes, and they're now live on the Source Functions page.
