### ISSUE TITLE
[Content]: HotJar accepts Track Events now

### ISSUE THREAD

**Issue by ashton-huxtable** [segmentio/segment-docs#3077]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/hotjar/

### What part(s) of the article would you like to see updated?

The HotJar integration was recently updated to accept[ Track events](https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/hotjar/lib/index.js#L77-L83).

The PR for this update can be found [here](https://github.com/segmentio/analytics.js-integrations/pull/660)

Docs should be updated to reflect these changes and prevent any confusion for customers.

**Comment by markzegarelli** [comment]
Hi @ashton-huxtable,

As is the case with SatisMeter, these changes need to be made in Partner Portal so that they reflect accurately in the docs.

**Comment by ashton-huxtable** [comment]
@markzegarelli  thanks I will look into this

**Comment by cmastr** [comment]
Closing issue as this fix needs to be done in another repo.
