### ISSUE TITLE
[Content]: conflicting information about which field is used for message deduplication

### ISSUE THREAD

**Issue by makarenkod** [segmentio/segment-docs#3194]
### What article on segment.com/docs is affected?

https://segment.com/docs/guides/duplicate-data/#warehouse-deduplication

### What part(s) of the article would you like to see updated?

We'd like to use deduplication functionality in our code but there is some conflicting information in Segment docs regarding which field should be used for this purpose.

https://segment.com/docs/guides/duplicate-data/#warehouse-deduplication
mentions `message_id`. 

On the other hand, 
https://segment.com/docs/connections/spec/common/#context
https://segment.com/blog/exactly-once-delivery/
mention 'messageId`.

To make it even more confusing, one of the mutual customers provided us message dumps that contain `messageid` field (i.e. all lower case).

Could you make sure it is consistent across all the docs?

**Comment by forstisabella** [comment]
Hi @makarenkod, thanks for bringing this to our attention! I reached out to our warehouse engineers to see which field is used for deduplication: Segment itself uses `messageId` on ingest to deduplicate data, and warehouses use `id`, which is derived from the `messageId` field, for deduplication. I'll make sure the docs are updated with the correct information.
