### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by alex-braze** [segmentio/segment-docs#3228]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/braze/

### What part(s) of the article would you like to see updated?

Braze Source now supports EU region. When setting up the Current Connector within the Braze dashboard, the EU region can be selected by using the "Segment Region" dropdown
<img width="578" alt="Screen Shot 2022-07-13 at 8 55 02 AM" src="https://user-images.githubusercontent.com/62311500/179090100-a7c96cf4-be63-42b1-a25c-897bc49398ae.png">
.

**Comment by cmastr** [comment]
This issue seems to have been fixed as I see the EU region mentioned there now. 

https://segment.com/docs/connections/sources/catalog/cloud-apps/braze/

**Comment by cmastr** [comment]
PR that fixed - https://github.com/segmentio/segment-docs/pull/4743
