### ISSUE TITLE
[Content]: Personas Profile API Reference

### ISSUE THREAD

**Issue by piohhmy** [segmentio/segment-docs#3372]
### What article on segment.com/docs is affected?

https://segment.com/docs/personas/profile-api/#api-reference

### What part(s) of the article would you like to see updated?

> The return limit for the /links endpoint is 20 records. You can request up to 20 records by appending ?limit=20 to the query string.

Should this instead be the following?
> The return limit for the /links endpoint is 20 records. You can request up to 200 records by appending ?limit=200 to the query string.

**Comment by pwseg** [comment]
@piohhmy The return limit for this endpoint is, indeed, 20 records.  We've updated the wording to be a little clearer about it, though.  Thanks for bringing this to our attention.
