### ISSUE TITLE
[Content]: Explain that email is a required property in Mixpanel (Actions)

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#3382]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-mixpanel/

### What part(s) of the article would you like to see updated?

The Mixpanel Actions destination requires that you map the email field so that Mixpanel recognizes it as their reserved email property, as shown in the payload & photos below : 

**Here's a payload I sent to Mixpanel (Actions)**
{
  "traits": {
      "email":"julie.st.cloud@testing.com",
      "name":"Julie St Cloud",
      "lastName":"St Cloud",
      "firstName":"Julie"
  },
  "type": "identify",
  "userId": "999-777-333-ff-jj"
}
 

**Here's the Mixpanel Actions Mapping**
![audyo - Mixpanel Actions - Mappings - Identify - $email](https://user-images.githubusercontent.com/68755692/185509787-751678db-4f89-4147-9ce2-1f487e3c4079.png)

**Here's the result in Mixpanel**
![audyo - Mixpanel Actions - $email](https://user-images.githubusercontent.com/68755692/185509796-38dafba6-1efc-448b-b5f5-607aa5054902.png)

**Comment by lizkane222** [comment]
If email is not mapped to $email in the Actions mapping then email will be undefined

**Comment by stayseesong** [comment]
@lizkane222 here's a preview of the fix:  https://deploy-preview-3463--segment-docs.netlify.app/connections/destinations/catalog/actions-mixpanel/#mappings

does this work?
