### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by peter-coastpay-com** [segmentio/segment-docs#3439]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/

### What part(s) of the article would you like to see updated?

Is there a way to override the 'host' url that segment requests are sent to?

**Comment by markzegarelli** [comment]
Hi @peter-coastpay-com,

Please [contact support ](https://segment.com/help/contact/)with this question, they will be best equipped to help you out.

Closing this issue for now, but will work with them to update the docs as needed.
