### ISSUE TITLE
[Content]: sample code to import Segment Python Analytics library

### ISSUE THREAD

**Issue by lyndonwong** [segmentio/segment-docs#3505]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/server/python/

### What part(s) of the article would you like to see updated?

**Getting Started section** of Analytics for Python:
https://segment.com/docs/connections/sources/catalog/libraries/server/python/#getting-started

The doc currently provides the following sample code to install and import the Segment library:

> Install segment-analytics-python using pip:
> `pip install segment-analytics-python`
>If you’re using a system for managing dependencies, you’ll want to pin the library to 1.X to avoid breaking changes when the library is updated
>
>Inside your app, you’ll want to set your write_key before making any analytics calls:
>
> `import analytics`
>
> `analytics.write_key = 'YOUR_WRITE_KEY'`

Should the python import statement be reworded as follows?

`import segment.analytics as analytics`

While learning how to use the Segment Python library using Replit, I could not call the Identify and Track api's until I made the above change to the "import" statement.

https://replit.com/@lyndonwong/Flask-web-form-v1#main.py

**Comment by pwseg** [comment]
@lyndonwong We've corrected this; thanks for bringing it to our attention.

**Comment by lyndonwong** [comment]
@pwseg glad to help. thx for the update.
