### ISSUE TITLE
[Content]: https://segment.com/docs/connections/sources/catalog/libraries/server/python/

### ISSUE THREAD

**Issue by percolatorly** [segmentio/segment-docs#3558]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/server/python/

### What part(s) of the article would you like to see updated?

Typo: Segemet should be Segment

**Comment by pwseg** [comment]
@percolatorly We've fixed this.  Thanks for letting us know!
