### ISSUE TITLE
[Bug]: Broken links and notion deal redemption does not work

### ISSUE THREAD

**Issue by ManuelBuri** [segmentio/segment-docs#3705]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/guides/usage-and-billing/startup-program/

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

Hi folks, the link https://bit.ly/segment-partner-deals does not work anymore and/or it needs a password to access it. Can you please look into this? Also Notion seems to be listed as a partner and one cannot redeem any deals with them. Thanks so much. Manuel

**Comment by markzegarelli** [comment]
Closing this for now, as the link is removed.
