### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by lizkane-twilio** [segmentio/segment-docs#3727]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-salesforce/

### What part(s) of the article would you like to see updated?

For multiple mappings, it states "__ is a Cloud action. The default Trigger is:" but then nothing is not listed. 

This is missing for **[Custom Object](https://segment.com/docs/connections/destinations/catalog/actions-salesforce/#custom-object)**, **[Contact](https://segment.com/docs/connections/destinations/catalog/actions-salesforce/#contact)**, **[Opportunity](https://segment.com/docs/connections/destinations/catalog/actions-salesforce/#opportunity)**, **[Case](https://segment.com/docs/connections/destinations/catalog/actions-salesforce/#case)**

For reference of what it's supposed to look like, check out  **[Account](https://segment.com/docs/connections/destinations/catalog/actions-salesforce/#account)** action, it has default trigger is `type = group`.

**Comment by markzegarelli** [comment]
Thanks @lizkane-twilio. These Actions don't have a default trigger, which I didn't know was possible. I will update the template to prevent the text from showing.
