### ISSUE TITLE
[Content]: Typewriter Support Update

### ISSUE THREAD

**Issue by derberbaby** [segmentio/segment-docs#3791]
### What article on segment.com/docs is affected?

https://segment.com/docs/protocols/apis-and-extensions/typewriter/

### What part(s) of the article would you like to see updated?

Want to include support for react-native as well according to this release: https://github.com/segmentio/typewriter/releases/tag/v8.0.0

**Comment by markzegarelli** [comment]
@stayseesong Can you take a look at this one when you have a moment?

**Comment by stayseesong** [comment]
@derberbaby React Native is included in the docs here: https://segment.com/docs/protocols/apis-and-extensions/typewriter/#react-native-quickstart
