### ISSUE TITLE
[ReactNative]: There's no example of what the Default Settings prop should look like.  

### ISSUE THREAD

**Issue by jsweird** [segmentio/segment-docs#3802]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#getting-started

### What part(s) of the article would you like to see updated?

In the props for the createClient method, it doesn't provide an example of what defaultSettings might look like, thus making the prop essentially worthless. If we could get insight into what that does and how to use it, that would be wonderful.

Additionally, iOS's App Tracking permission could potentially flag this functionality as non-compliant if we don't have a way to pass a prop into the client. Ideally we have a function that we can set once the app has had a chance to determine whether the user accepts App tracking, and this controls the way Segment behaves. Trying to conditionally create the Client based on this permission causes the app to not function in the event we don't want to track.

**Comment by markzegarelli** [comment]
hi @jsweird, in talking with our engineering team about this issue, they recommended that you create a [support ticket](https://segment.com/help/contact/) for this request, to ensure your implementation goes as smoothly as possible. I'll then use the information gathered through that process to update the docs.
