### ISSUE TITLE
[Content]: Modern Pricing

### ISSUE THREAD

**Issue by h-parker-higgins** [segmentio/segment-docs#3831]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/modern-pricing/

### What part(s) of the article would you like to see updated?

Modern Pricing is defunct. They haven't been a company/product for about 2 Years. The only presence online is the Segment Destination documentation for Modern Pricing. 

This page, https://segment.com/docs/connections/destinations/catalog/modern-pricing/, should be removed. 

https://modernpricing.com/

**Comment by markzegarelli** [comment]
Thanks @h-parker-higgins, we've removed this page from the site, and deprecated the destination in Segment's catalog.

**Comment by h-parker-higgins** [comment]
Thanks Mark. It's a bummer. Was a really cool product.
