### ISSUE TITLE
[Content]: Make user_id a required argument for group calls

### ISSUE THREAD

**Issue by vinayak-mehta** [segmentio/segment-docs#3926]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/spec/group/

### What part(s) of the article would you like to see updated?

Opening this issue here because I'm not sure where else to open it in the Segment github org.

The first line of the [Spec: Group](https://segment.com/docs/connections/spec/group/) doc states that: 

```
The group API call is how you associate an individual user with a group—be it a company, organization, 
account, project, team or whatever other crazy name you came up with for the same concept!
```

We've built company analytics at https://github.com/juneHQ based on a `group` call associating a user with a group. But since `user_id` is not a required parameter for `group` calls, we've seen our users send `group` calls without it, leading to multiple support tickets to dig into why they can't see users in their group inside June.

What do you think about making `user_id` a required parameter for `group` calls in the Segment SDKs?

**Comment by markzegarelli** [comment]
Hi @vinayak-mehta, thanks for the ticket.

Your question might be better suited to ask to Support, as this channel is for documentation updates specifically.

Please reach out to https://segment.com/help/contact/, and they will be able to better take action on this.
