### ISSUE TITLE
[Intercom destination]: A link in the document is not working

### ISSUE THREAD

**Issue by deepdel** [segmentio/segment-docs#3977]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/intercom/#client

### What part(s) of the article would you like to see updated?

Under https://segment.com/docs/connections/destinations/catalog/intercom/#client, there is a link for Intercom contact model documentation(https://developers.intercom.com/intercom-api-reference/reference/contacts-model) which is not working, as the page doesn't exist.

**Comment by pwseg** [comment]
@deepdel Thanks for noticing this. We've gone ahead and made that fix; it appears Intercom migrated their docs recently, which broke a lot of the links on this page.

Just a heads up: the Intercom Destination is in maintenance mode, and Intercom has deprecated some previously available resources, like the [user model](https://developers.intercom.com/intercom-api-reference/reference/users).
