### ISSUE TITLE
[Content]: Include limits of CSV Downloader to docs

### ISSUE THREAD

**Issue by 050phy** [segmentio/segment-docs#4091]
### What article on segment.com/docs is affected?

https://segment.com/docs/engage/audiences/#download-your-audience-as-a-csv-file

### What part(s) of the article would you like to see updated?

There's 5 minute limit per user (regardless of audience/trait) for generating CSVs for download. We do not call out this limit in the docs.

Slack message here for the confirmation by Product team: https://twilio.slack.com/archives/C7F3N3RV4/p1674139220167099?thread_ts=1674111115.672829&cid=C7F3N3RV4

**Comment by rchinn-segment** [comment]
Hi @050phy, thanks for flagging. I’m going to hold off on this update because it has been [identified as an edge case](https://twilio.slack.com/archives/C7F3N3RV4/p1674513523711489) that applies to a few workspaces, and not rolled out to all.
