### ISSUE TITLE
[Bug]:  Commented Line never commented

### ISSUE THREAD

**Issue by jsabor** [segmentio/segment-docs#4146]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/storage/data-lakes/lake-formation/

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

After the first paragraph the commented line is displaying:
`<!– PW: 9/22/22; commenting this section out for GA`

**Comment by pwseg** [comment]
@jsabor We've gone ahead and fixed this. Thanks for bringing it to our attention.
