### ISSUE TITLE
Hubspot Company Search Fields - exact match

### ISSUE THREAD

**Issue by volneyvj** [segmentio/segment-docs#4157]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-hubspot-cloud/#upsert-company

### What part(s) of the article would you like to see updated?

Inside Upsert Company section table, at ' Company Search Fields ' is written: 

" The unique field(s) used to search for an existing company in HubSpot to update. By default, Segment creates a custom property to store groupId for each company and uses this property to search for companies. If a company is not found, the fields provided here are then used to search. If a company is still not found, a new one is created.  "

I would suggest adding to the last line that field value must be excat match, which differs from the classic hubspot destination version, where you could query just part of the value to find the company (for example: without the https:// for domain).

it would be result something like:
' The unique field(s) used to search for an existing company in HubSpot to update. By default, Segment creates a custom property to store groupId for each company and uses this property to search for companies. If a company is not found, the fields provided here are then used to search (field value must be exact match). If a company is still not found, a new one is created.  '

**Comment by markzegarelli** [comment]
@volneyvj The content for these fields come directly from the destination code. For example, the source for this destination, action, and field is [here](https://github.com/segmentio/action-destinations/blob/0704ee51d22f53bb585b7d584dd54728d43908ed/packages/destination-actions/src/destinations/hubspot/upsertCompany/index.ts#L156).

Once the fields is updated and deployed to prod, docs will pull it in on our next deploy.

I think your update makes sense, but closing this issue as it's out of our scope.
