### ISSUE TITLE
[Content]: duplicate proxy entry?

### ISSUE THREAD

**Issue by onlywei** [segmentio/segment-docs#4220]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

### What part(s) of the article would you like to see updated?

In the "Using a Custom Proxy" section, Option 1. It says:

> Option 1: Update the proxy so that:
> https://cdn.yourdomain.com/analytics.js/* maps to https://cdn.segment.com/analytics.js/* 
> https://cdn.yourdomain.com/analytics.js/* maps to https://cdn.segment.com/v1/* 
> https://cdn.yourdomain.com/analytics-next/* maps to https://cdn.segment.com/analytics-next/*
> https://cdn.yourdomain.com/next-integrations/* maps to https://cdn.segment.com/next-integrations/*

However, the first two URLs are identical. They are both: `https://cdn.yourdomain.com/analytics.js/*`. Which of the two destinations is this URL supposed to be mapped to?

**Comment by sarahrudy** [comment]
Hi @onlywei, thanks for pointing this typo out. This has been [fixed](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#:~:text=https%3A//cdn.yourdomain.com/v1,https%3A//cdn.segment.com/v1/*) in our docs.
