### ISSUE TITLE
[Content]: Update Authentication Process

### ISSUE THREAD

**Issue by prigiattiperrut** [segmentio/segment-docs#4319]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/stitch-data/

### What part(s) of the article would you like to see updated?

On the settings section where we say:

> In your Stitch dashboard, click ‘Add an Integration’. Click on Segment, and complete the ‘Enable with Segment’ workflow.

Change the notes to: 

> While signed into Segment as a Workspace Owner or Source Admin, go to your Stitch dashboard, click ‘Add an Integration’. Click on Segment, and complete the ‘Enable with Segment’ workflow.

So customers don’t run into permission issues when trying to authenticate without the right permissions.

**Comment by markzegarelli** [comment]
Hi @prigiattiperrut. Text content for settings, like in the example you highlighted, are pulled directly from the integration metadata, and can be updated in Partner Portal.

Docs team does not have access to this though. Closing, as we cannot fix this directly.
