### ISSUE TITLE
[Bug]: Search engine brings user to incorrect part of page

### ISSUE THREAD

**Issue by sarahrudy** [segmentio/segment-docs#4326]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/destination-data-control/#export-your-source-schema

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

Hi team! I noticed sometimes when I search for a general topic in the Segment docs, then click on it ("source schema" for example), it takes me to a very specific part of that page, when really it should probably take me to the top of the [Using Schema Controls](https://segment.com/docs/connections/destination-data-control/) page. 

For example, I searched for "source schema" (image below) trying to get to the top of the general page, but when I click on "Using Schema Controls", it takes me to the part of the page that says "[Export your Source Schema](https://segment.com/docs/connections/destination-data-control/#export-your-source-schema)", which isn't really related to what I was searching for. If I was a customer, it might be confusing?

![image](https://user-images.githubusercontent.com/78389005/221976599-346355f8-db59-4474-b8ea-157ddb032e1b.png)

**Comment by sarahrudy** [comment]
Hi there! I found another page where the docs search brings me to the middle of the page instead of the top. When I search for "Eloqua", you can see the search result that pops up is the `page` call section of the documentation, but I'm expecting it to take me to the top of the page. 

<img width="716" alt="Screenshot 2023-03-08 at 2 45 40 PM" src="https://user-images.githubusercontent.com/78389005/223857562-1baf31a3-7c09-468b-ad67-c43d482c3be9.png">

**Comment by forstisabella** [comment]
closing this, as it looks like both the Eloqua destination and the Source Schema page direct to the top of the page!
