### ISSUE TITLE
[Bug]: Missing link on Google Ads (Classic) page

### ISSUE THREAD

**Issue by sarahrudy** [segmentio/segment-docs#4336]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/destinations/catalog/google-ads-classic/#mobile--server:~:text=Google%20Ads%20(Classic)%20has%20plans%20to%20deprecate%20the%20API%20that%20the%20functionality%20outlined%20here%20relies%20on.%20Reference%20the%20documentation%20that%20supports%20their%20new%20API%20version%20above.

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

<img width="718" alt="Screenshot 2023-03-01 at 4 09 32 PM" src="https://user-images.githubusercontent.com/78389005/222287529-bef14937-2080-4795-9cf0-4b3459152017.png">

Should *here* have a link, or was this intentional? 

Even though this destination is outdated, this is important as customers look to upgrade and need to know which functionality is getting deprecated

**Comment by markzegarelli** [comment]
"Here" should say "below". I will update it.
