### ISSUE TITLE
[Content]: Missing Info on "Naming Conventions" (Analytics Academy) article

### ISSUE THREAD

**Issue by sarahrudy** [segmentio/segment-docs#4359]
### What article on segment.com/docs is affected?

https://segment.com/academy/collecting-data/naming-conventions-for-clean-data

### What part(s) of the article would you like to see updated?

I'm not entirely sure what should belong here instead, but it looks like [this part of the article](https://segment.com/academy/collecting-data/naming-conventions-for-clean-data/#:~:text=Putting%20this%20all,something%20like%20this%3A) is possibly missing some information: 

> Putting this all together, it's really easy to construct your events.
> 
> Here is the naming template we adhere to:
> 
> And here is a sample event, Product Viewed:
> 
> Document these events in your [tracking plan](https://segment.com/academy/intro/how-to-create-a-tracking-plan/) and make sure to implement them in code with the same formatting.
> 
> In code, it would look something like this:

**Comment by forstisabella** [comment]
Hi @sarahrudy - the Digital team owns the segment.com/academy page and are looking into this now!

**Comment by forstisabella** [comment]
The Digital team fixed it!
