### ISSUE TITLE
[Content]: opening paragraph

### ISSUE THREAD

**Issue by daveo237** [segmentio/segment-docs#4396]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/google-tag-manager/#getting-started

### What part(s) of the article would you like to see updated?

opening paragraph : 
[Google Tag Manager](https://support.google.com/tagmanager) (GTM) is a tag management system that allows you to quickly and easily update tags and code snippets on your website or mobile apps. Once you add the Tag Manager snippet to your website or mobile app, you can configure tags using a web-based user interface without having to alter and deploy additional code. This reduces errors and frees you from having to involve a developer whenever you need to make changes. The Google Tag Manager Destination is open-source. You can browse the code [on GitHub](https://github.com/segment-integrations/analytics.js-integration-google-tag-manager).

GTM does not support mobile devices can this section be altered to remove the mobile sections leas

**Comment by forstisabella** [comment]
Addressed with changes made in #4509!
