### ISSUE TITLE
[Content]: Audience definition does not match Description of audience in the doc

### ISSUE THREAD

**Issue by anver-trip** [segmentio/segment-docs#4566]
### What article on segment.com/docs is affected?

https://segment.com/docs/engage/quickstart/#step-5-create-an-audience

### What part(s) of the article would you like to see updated?

Description of audience in the doc says: 
The Audience Builder UI prompts you to filter your users using on specific behaviors that they performed. The audience in the example below is all the users who have performed the event User Signed Up at least one time within the last 7 days.

Image shows condition "Did not perform Order completed exactly 1 time in last 7 days".

**Comment by pwseg** [comment]
@anver-trip Thanks for letting us know about this; we've gone ahead and fixed it.
