### ISSUE TITLE
[Content]: Adding in how to switch to Subusers for Sendgrid

### ISSUE THREAD

**Issue by jpang007** [segmentio/segment-docs#4649]
### What article on segment.com/docs is affected?

https://segment.com/docs/engage/onboarding/

### What part(s) of the article would you like to see updated?

The article contains references to how to create a subuser account, however it could be improved if it mentions the importance of switching over to the subuser before generating API keys. Since on both the main and subuser account you are able to generate API keys, sometimes customers don't understand the difference of operating under the subuser. Specifically this section of the article, it's easy to miss the step of "on the subuser account". 

A customer suggested adding this documentation in as well for reference to Sendgrid specifically: https://docs.sendgrid.com/ui/account-and-settings/subusers#create-a-subuser

**Comment by pwseg** [comment]
@jpang007 Thanks for letting us know about this.  I've added a callout in the **Generate an API key** section.  The callout reminds users that they'll need to be in their subuser space before generating the API key.  I also added a link to the SendGrid documentation you added here. Hopefully this will help clarify things.
