### ISSUE TITLE
[Content]: Mixpanel Cohorts to Engage User Profile

### ISSUE THREAD

**Issue by ginu-kuncheria** [segmentio/segment-docs#4669]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/mixpanel-cohorts/

### What part(s) of the article would you like to see updated?

Can we please a section for what needs to be done to get this data into Engage. (You have to go into Engage and add the newly created MixPanel Cohorts Source as a Source in Unify Settings)

**Comment by rchinn-segment** [comment]
Thanks for raising, @ginu-kuncheria. We'll get this update into our next docs deploy (5/9).
![4669-Mixpanel Cohorts 2](https://user-images.githubusercontent.com/93161299/236521687-52795567-bebf-452b-ad12-331c86925db5.png)
