### ISSUE TITLE
[Bug]: Link to Edge Functions broken

### ISSUE THREAD

**Issue by Kal-Segment** [segmentio/segment-docs#4777]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/#device-mode-transformations--filtering

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

The link for Edge Functions seems to just link to the same page.

**Comment by forstisabella** [comment]
Looks like this was fixed in #4785!
