### ISSUE TITLE
[Bug]: https://segment.com/docs/connections/spec/identify/

### ISSUE THREAD

**Issue by kerolloz** [segmentio/segment-docs#4810]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/spec/identify/

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

Note not rendered properly. 

<img width="1362" alt="Screenshot 2023-05-28 at 4 37 28 PM" src="https://github.com/segmentio/segment-docs/assets/36763164/6f060278-f5f3-4670-b7e2-c79f24db2f41">

**Comment by forstisabella** [comment]
Closing this, as I can't replicate the bug. If it occurs again, please feel free to reopen this issue!
