### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by nabucho** [segmentio/segment-docs#4873]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/exponea/

### What part(s) of the article would you like to see updated?

All references to **Exponea** should be changed to "**Bloomreach Engagement**".
Exponea was acquired by Bloomreach in 2021 and product was renamed after. 
( proof - click on any links on current page for redirects to bloomreach.com page ).
Links to www.exponea.com should be changed to https://www.bloomreach.com/en/products/engagement
Lins to API groups ( https://docs.exponea.com/reference#setting-up-access-keys )  should be changed to https://documentation.bloomreach.com/engagement/reference/authentication
group permissions to https://documentation.bloomreach.com/engagement/reference/authentication#using-the-api-groups

Links for automatic session tracking changed to https://documentation.bloomreach.com/engagement/docs/system-events#section-first-session-session-start-session-end

Thank you for understanding and this branding change. Functionality is identical, everything else is the same.

**Comment by forstisabella** [comment]
Hi @nabucho, is the support email that's currently on the page still correct (support@exponea.com), or is there a new email I should include?

**Comment by nabucho** [comment]
As confusing as it sounds, yes the email remains the same....

Also, can we remove the Beta designation as well while on it? 
And redirect the URL from https://segment.com/docs/connections/destinations/catalog/**exponea** to https://segment.com/docs/connections/destinations/catalog/**bloomreach** ?

**Comment by tcgilbert** [comment]
![Screen Shot 2023-07-10 at 3 16 02 PM](https://github.com/segmentio/segment-docs/assets/64277654/08f0d8c8-f2c5-4adb-83c3-36f5a78bb0b4)

Hey @nabucho - I'll be updating the name for the integration. Do you have a mark and default logo for the integration we could use? These will need to be in SVG format

**Comment by nabucho** [comment]
Look if these work 

![Primary Linear Logo](https://github.com/segmentio/segment-docs/assets/192888/e4a328c3-6848-4641-8fe7-e46708dbc626)
![Primary Brand Icon](https://github.com/segmentio/segment-docs/assets/192888/20424834-4e3f-4830-936b-e15e6a28c102)
![Primary Stacked Logo](https://github.com/segmentio/segment-docs/assets/192888/d5d905fc-d1ad-4c7c-8464-9df2eb1067fb)

**Comment by nabucho** [comment]
[Archive.zip](https://github.com/segmentio/segment-docs/files/12006183/Archive.zip)

**Comment by tcgilbert** [comment]
thanks @nabucho - I've update Exponea to Bloomreach Engagement in our internal catalog. @forstisabella you can go ahead with the doc changes now

**Comment by forstisabella** [comment]
Perfect - thank you so much @tcgilbert!!
