### ISSUE TITLE
[Bug]: Best practices to identify user

### ISSUE THREAD

**Issue by sandilya-45** [segmentio/segment-docs#4949]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/spec/best-practices-identify/

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

In the Full user registration step where you say, after user is fully registered then UserId will be populated. But in the shown payload, UserId is still null. It is confusing. Please look at the issue. Thank you.

**Comment by forstisabella** [comment]
Resolved in #5012!
