### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by HemaThanki** [segmentio/segment-docs#5008]
### What article on segment.com/docs is affected?

https://segment.com/docs/guides/regional-segment/

### What part(s) of the article would you like to see updated?

Under [this](https://segment.com/docs/guides/regional-segment/#regional-data-ingestion) section we should update:

Cloud event sources aren’t supported in EU workspaces.

TO:

Some [cloud event]([Cloud event](https://segment.com/docs/connections/sources/#event-cloud-sources)) sources aren’t supported in EU workspaces.

**Comment by forstisabella** [comment]
Hi @HemaThanki - I did some digging in our sources catalog (generated by PAPI) at it looks like the only source that is a cloud event source/has EU regions and endpoints is Factual Engine, and then Mixpanel Cohorts has an EU region but not an EU endpoint. How is support for EU workspaces determined?
