### ISSUE TITLE
[Content]: HubSpot Cloud Mode (Actions) Destination

### ISSUE THREAD

**Issue by lp2485** [segmentio/segment-docs#5027]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-hubspot-cloud/#hubspot-cloud-mode-actions-destination

### What part(s) of the article would you like to see updated?

[BEFORE the 5 steps](https://segment.com/docs/connections/destinations/catalog/actions-hubspot-cloud/#getting-started) , there should be a mention that a Hubspot Private App needs to be created and it needs to have the following scopes: 

- business-intelligence, 
- crm.objects.contacts.read, 
- crm.objects.contacts.write, 
- crm.schemas.contacts.read, 
- crm.objects.companies.read, 
- crm.objects.companies.write, 
- crm.schemas.companies.read.

**Comment by varadarajan-tw** [comment]
Hello @lp2485 / @rchinn-segment – I just noticed the update made to HubSpot Cloud Mode docs. I am a Segment developer who built this destination. HubSpot Cloud Mode action doesn't support `Private Apps`. Private Apps is only supported for the non-actions version of the destination and its relevant docs are [here]. (https://github.com/segmentio/segment-docs/blob/develop/src/connections/destinations/catalog/hubspot/index.md). HubSpot Cloud Mode action supports only OAuth.
Can we revert this change to avoid confusion?

**Comment by lp2485** [comment]
@varadarajan-tw I am happy to send you the full support ticket (see screenshot below). The only way I was able to connect segment cloud mode was via private app. 

![image](https://github.com/segmentio/segment-docs/assets/15224171/369eceb1-551c-426c-aa71-9d56551c8d84)

**Comment by lp2485** [comment]
also @varadarajan-tw take a second look at the link you sent me... https://github.com/segmentio/segment-docs/blob/develop/src/connections/destinations/catalog/hubspot/index.md#:~:text=info%20%22%22%20As%20of,%7B%3Atarget%3D%22_blank%22%7D.

**Comment by varadarajan-tw** [comment]
Thanks for sharing the context @lp2485, and also thank you for taking time to update the docs. 🙏 

On the week of July 14th, we had an issue with OAuth in our HubSpot Cloud mode destination, and it was resolved after. I understand this was shared during the period for you to set up. But, it is no longer required to set up Private Apps for using HubSpot cloud mode action and setting it up will no longer have impact on the destination's connection with HubSpot. The only action needed is to Connect via OAuth. Let me know if you have any other questions.
