### ISSUE TITLE
[Content]: Correct the description for livestream parameter in "Content event object" 

### ISSUE THREAD

**Issue by thepanda919** [segmentio/segment-docs#5052]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/spec/video/#content-event-object

### What part(s) of the article would you like to see updated?

It appears as though you copied/pasted the latter half of the description from the position parameter. The livestream parameter is a boolean & isn't relative to the playhead position.

### Additional information

![image](https://github.com/segmentio/segment-docs/assets/111533892/a80b4c01-034a-4cd4-abc5-a0cef866aaa0)

**Comment by stayseesong** [comment]
@thepanda919 The description of livestream was also included for `position` so that if users are curious about the playhead position for a livestream, they'll know it's a bit different

**Comment by thepanda919** [comment]
any update on this?

**Comment by stayseesong** [comment]
@thepanda919 I've put the fix in this PR #5558
