### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by t2b2015** [segmentio/segment-docs#5121]
### What article on segment.com/docs is affected?

https://segment.com/docs/segment-app/iam/audit-trail/

### What part(s) of the article would you like to see updated?

Add Business Tier tick at the top of the page similar to https://segment.com/docs/guides/regional-segment/
To show customers what tier's this feature is available to and keep our docs coherent across the board.

### Additional information

<img width="439" alt="Screenshot 2023-08-03 at 13 07 15" src="https://github.com/segmentio/segment-docs/assets/115621880/5fb97cab-3acc-4309-8639-aa6b9516ecd2">

**Comment by forstisabella** [comment]
@t2b2015 - this is an add-on for business tier customers, correct?
