### ISSUE TITLE
Hyperlink for "enable the Slack destination" leads to the old Slack destination. It needs to re-direct user to the new Slack(Actions) destination

### ISSUE THREAD

**Issue by shraddha1313** [segmentio/segment-docs#5131]
### What article on segment.com/docs is affected?

https://segment.com/docs/protocols/apis-and-extensions/anomaly_detection/#forward-violations-to-a-slack-channel

### What part(s) of the article would you like to see updated?

- Give as much detail as you can to help us understand the change you want to see
If I would like to forward violations to Slack, the FAQs [here](https://segment.com/docs/protocols/faq/#how-do-i-get-notified-when-new-violations-are-generated-can-i-create-custom-violation-notifications) state that I need to use the Slack (Actions) destination. However the new destination recommendation is not reflected [here](https://segment.com/docs/protocols/apis-and-extensions/anomaly_detection/#forward-violations-to-a-slack-channel) under "enable a Slack destination". The hyperlink re-directs users to the old Slack destination
- Why should the docs be changed? What use cases does it support?
To reflect the most recent Actions framework destination for Slack
- What is the expected outcome?
The most recent information gets updated in our docs

Please let me know if you have any questions.

**Comment by forstisabella** [comment]
hi @shraddha-twilio - it looks like Slack (Actions) doesn't support the handlebars syntax that Slack Classic does, and the code sample/screenshot on the Anomaly Detection both use the handlebarsjs format. Do we need a new code snippet and screenshot for this page, or is Slack Classic supported here?

**Comment by shraddha1313** [comment]
My understanding was that this could be achieved using the Slack (Actions) destination based on the slack thread [here](https://twilio.slack.com/archives/C9Z93GW76/p1673371378806009?thread_ts=1673368066.678069&cid=C9Z93GW76). Let me know if that isn't the case.

**Comment by forstisabella** [comment]
hi @shraddha1313 - can you take a look at this PR (#5162) and see if it's all accurate? Thanks!
