### ISSUE TITLE
[Content]: Update CleverTap doc - only support device-mode for web connection

### ISSUE THREAD

**Issue by joeynmq** [segmentio/segment-docs#5164]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/clevertap/#clevertap-destination

### What part(s) of the article would you like to see updated?

Currently, our public doc indicates that CleverTap Destination supports both device-mode and cloud-mode for web connections:
<img width="724" alt="image" src="https://github.com/segmentio/segment-docs/assets/37472597/f98b0bab-447d-4d02-9b0d-3e1a0cfaf388">

However, when connecting CleverTap to web analytics.js, it seems that the integration only operates in device-mode.

### Additional information

Relevant past tickets: [#479122](https://segment.zendesk.com/agent/tickets/479122), [#484355](https://segment.zendesk.com/agent/tickets/484355)

**Comment by forstisabella** [comment]
@joeynmq looks like we had issue submitted for this destination saying that it supports all cloud mode connections (#2303) - I'm happy to manually override those changes if that's not the case! (I can't see the Zendesk tickets)

**Comment by joeynmq** [comment]
@forstisabella yup that's right, thanks :)

**Comment by forstisabella** [comment]
Closed by #5210!
