### ISSUE TITLE
[Content]: Settings listed twice on Facebook Pixel page

### ISSUE THREAD

**Issue by sarahrudy** [segmentio/segment-docs#5175]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/facebook-pixel/#settings

### What part(s) of the article would you like to see updated?

<img width="251" alt="Screenshot 2023-08-10 at 11 07 03 PM" src="https://github.com/segmentio/segment-docs/assets/78389005/25fc5ba6-f0c5-46ac-896b-84d5fb1ab6f7">

"Settings" is listed twice in right-hand column of page

**Comment by pwseg** [comment]
@sarahrudy We've fixed this, thanks for letting us know.
