### ISSUE TITLE
[Content]: 

### ISSUE THREAD

**Issue by HemaThanki** [segmentio/segment-docs#5179]
### What article on segment.com/docs is affected?

https://segment.com/docs/guides/regional-segment/

### What part(s) of the article would you like to see updated?

Update the intro, please see doc here: https://docs.google.com/document/d/1mwZmVCrcBc6fOerGQxAvTF9xkXCGlwMzFYeA3XpJ9us/edit

**Comment by stayseesong** [comment]
@HemaThanki I've created a PR for this request here: #5199
