### ISSUE TITLE
[Content]: Discrepancy with Ingestion rate limit

### ISSUE THREAD

**Issue by shraddha1313** [segmentio/segment-docs#5216]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#rate-limits:~:text=not%20exceeding%20500%20requests%20per%20second

### What part(s) of the article would you like to see updated?

Hi Team,

It looks like there's discrepancy with the ingestion rate limit mentioned in our docs.

The article [here](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/) states that "Segment recommends not exceeding 500 requests per second".
However the Product limits page [here](https://segment.com/docs/connections/rate-limits/#:~:text=60%20million%20events%20in%20any%20ten%20minute%20period) seems to indicate that Segment can ingest "60 million events in any ten minute period". 

A difference of 500 events per second versus 100K events per second is a huge discrepancy and it raised some alarms with a client that I was speaking to. My understanding is that Segment can ingest up to 100K events per second. 

Could you please rectify this error in the [HTTP API source](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/) docs and clearly mention the 100K events per second limit for our streaming API endpoint and the 500 KB per request limit for the batch endpoint?

Thanks,
Shraddha

**Comment by rchinn-segment** [comment]
Thanks for flagging this, @shraddha1313! We'll include this fix in our upcoming docs deploy (8/22).
