### ISSUE TITLE
[Content]: Add note for Set Configuration Fields action

### ISSUE THREAD

**Issue by joeynmq** [segmentio/segment-docs#5258]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-google-analytics-4-web/#set-configuration-fields

### What part(s) of the article would you like to see updated?

Expected outcome (See **bold** for amendment):

> Set Configuration Fields
> 
> Set custom values for the GA4 configuration fields, **and trigger a page_view event**.
> 
> Set Configuration Fields is a Web action. The default Trigger is: type = "identify" or type = "page"

### Additional information

When sending Identify events to GA4 using the Set Configuration Fields mapping, the customer is confused about why a page_view event should be triggered.

Checking the integration code here - https://github.com/segmentio/action-destinations/blob/main/packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts#L139 

We always send page_view  to Google when using the Set Configuration Fields mapping, even the customers fire Identify calls (given that The default Trigger is: type = "identify" or type = "page").

JIRA: https://segment.atlassian.net/browse/KCS-522

**Comment by forstisabella** [comment]
HI @joeynmq - this content is autogenerated using PAPI. I don't think we can do an override for this like we can for the settings/slug for a destination, but I'll see if there's another repo (like actions-destinations) that you could make the update directly!

**Comment by forstisabella** [comment]
Closing, as it's not able to be fixed in the scope of this repo. If you'd like to see this updated, please open a PR In the action-destinations repo.
