### ISSUE TITLE
[Content]: Make how to promote IDFA as identifier more explicit

### ISSUE THREAD

**Issue by Kal-Segment** [segmentio/segment-docs#5317]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/adwords-remarketing-lists/

### What part(s) of the article would you like to see updated?

On paragraph 3 of the overview, it states: "If you use Segment’s mobile SDKs to collect events from a mobile app, the user’s IDFA is automatically captured. If you don’t use Segment’s mobile SDKs, you can set the user’s IDFA by setting it within context.device.advertisingId."

I've had a number of customers confused as to why Google Ads Remarketing List is still not receiving users into an audience. Can we make this more explicit by adding: "you are also required to collect context.device.type and context.device.adTrackingEnabled on the event payload. Additionally, ensure android.idfa / ios.idfa are enabled as identifiers in your Identity Resolution settings on Engage".

This will make it much clearer to customers who are having difficulties here.

**Comment by stayseesong** [comment]
hi @Kal-Segment, I created a PR for this here: #5557
