### ISSUE TITLE
[Content]: addSourceToTrackingPlan endpoint not only adds the TP to a source but also replaces the TP if there is an existing TP associated with the source

### ISSUE THREAD

**Issue by shraddha1313** [segmentio/segment-docs#5468]
### What article on segment.com/docs is affected?

https://docs.segmentapis.com/tag/Tracking-Plans#operation/addSourceToTrackingPlan

### What part(s) of the article would you like to see updated?

Hi,
There isn't much context around this endpoint.

My understanding was that this endpoint only helps adding a new tracking plan for a source. 

However, turns out this endpoint also helps replacing the existing tracking plan for a source with the new tracking plan. 

I think this needs to be highlighted in the docs for this endpoint. Otherwise a user might assume that we need to [first remove a source from the existing tracking plan](https://docs.segmentapis.com/tag/Tracking-Plans#operation/removeSourceFromTrackingPlan) and then [add a new tracking plan to that source](https://docs.segmentapis.com/tag/Tracking-Plans#operation/addSourceToTrackingPlan). 

Let me know if you have any questions. Thanks!

**Comment by forstisabella** [comment]
Hi @shraddha1313 - the Segment Docs team doesn't maintain the Public API docs. Your best bet would be to raise this in the Public API questions channel in Slack!
