### ISSUE TITLE
[Content]: Inflection Destination documentation has wrong details 

### ISSUE THREAD

**Issue by niranjana687** [segmentio/segment-docs#5493]
### What article on segment.com/docs is affected?

https://segment.com/catalog/integrations/inflection/

### What part(s) of the article would you like to see updated?

The page mentions that Inflection supports page, screen, identify and track calls, but Inflection only supports **Identify, group and track calls.**

**Comment by tcgilbert** [comment]
made pr to address: https://github.com/segmentio/segment-docs/pull/5525

**Comment by forstisabella** [comment]
Closed with the merge of #5525. thanks @tcgilbert!

**Comment by niranjana687** [comment]
Thank you!
