### ISSUE TITLE
[Content]: Alloy Flow change from object source to event source

### ISSUE THREAD

**Issue by gyeuttersegment** [segmentio/segment-docs#5707]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/sources/catalog/cloud-apps/alloyflow/

### What part(s) of the article would you like to see updated?

The Source is displaying as an object source, but I checked with the authors, and they say it's a streaming event source

**Comment by forstisabella** [comment]
Hi @gyeuttersegment - unfortunately this isn't something we can override in the docs. You'd need to make this change in the partner portal, as that is what the docs site uses to pull information about the source type.
