### ISSUE TITLE
[Content]: possible incorrect example on Unify profile sync docs

### ISSUE THREAD

**Issue by clancychilds** [segmentio/segment-docs#5820]
### What article on segment.com/docs is affected?

https://segment.com/docs/unify/profiles-sync/tables/

### What part(s) of the article would you like to see updated?

In "Event 3" in the example on this page, it states:
```
// Weeks later, an anonymous visit to twilio.com triggers a Page call:
anonymous_id: b50e18a5-1b8d-451c
context.url: twilio.com/education
timestamp: June 22, 10:47:15
email: jane.kim@segment.com
// Segment generates Profile 2, with a single known ID: b50e18a5-1b8d-451c.
```

However, if it was anonymous, the email wouldn't be in that page call. I think this is an error and the email should be removed from the example in Event 3.

**Comment by rchinn-segment** [comment]
Thanks for flagging this, @clancychilds! We'll include this update in our next docs deploy.
