### ISSUE TITLE
[Content]: Update the Kustomer destination's Engage section in docs  

### ISSUE THREAD

**Issue by MStephen024** [segmentio/segment-docs#5880]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/kustomer/#engage

### What part(s) of the article would you like to see updated?

The Kustomer destination is maintained by Kustomer. 

Per a past Zendesk ticket, it seems the Kustomer destination does not accept custom properties, only standard properties (name, phone, email, etc.). This prevents any traits Engage generated events from being added to a user's profile downstream, since the Audience's/Computed Trait's names will be considered custom traits (e.g. my_computed_trait_name).

Therefore, the template Engage section in the Kustomer destination docs are not accurate. Once the Kustomer integration is able to send/receive custom properties, the Engage section in the docs would apply to the destination.

**Comment by forstisabella** [comment]
Closing, as this was addressed in #5566
