### ISSUE TITLE
[Bug]: Code Section extends to next set of content.

### ISSUE THREAD

**Issue by qwilr-altonius** [segmentio/segment-docs#5995]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/#custom-proxy-setup

### What browsers are you seeing the problem on?

Chrome

### Please describe the issue.

I think the code section for the template email is too long here and extends into the next set of instructions.  I think the "Double Check the Source URL..." is the next heading.
<img width="733" alt="Screenshot 2024-02-06 at 4 46 06 pm" src="https://github.com/segmentio/segment-docs/assets/124948145/1ad99465-e769-40dd-a599-3022e65ff7b5">

**Comment by pwseg** [comment]
@qwilr-altonius Thanks for catching this, we've fixed this with #6021.
