### ISSUE TITLE
[Content]: Update Mixpanel Cohorts EU Workspace availability

### ISSUE THREAD

**Issue by t2b2015** [segmentio/segment-docs#6169]
### What article on segment.com/docs is affected?

https://segment.com/docs/guides/regional-segment/

### What part(s) of the article would you like to see updated?

https://segment.com/docs/guides/regional-segment/#source-regional-support

Currently advises EU Workspace is available for Mixpanel Cohort - it is not.

**Comment by tcgilbert** [comment]
put in a fix for this here: https://github.com/segmentio/segment-docs/pull/6172
