### ISSUE TITLE
[Bug]: DataBrick Reverse ETL - Failed to connect SQL Warehouse 

### ISSUE THREAD

**Issue by bigredbug47** [segmentio/segment-docs#6309]
### Where on segment.com/docs did you see this issue?

https://segment.com/docs/connections/reverse-etl/reverse-etl-source-setup-guides/databricks-setup/

### What browsers are you seeing the problem on?

Safari

### Please describe the issue.

Hi guys,

I got the reverse ETL connection between Segment and DataBricks SQL Warehouse. So, normally, the Segment will wait for the SQL warehouse to be turned on before executing the query and retrieving the data. 

However, since yesterday, (27-Mar) if the SQL warehouse is not in the running state, the reverse ETL will immediately return an error due to a timeout error. (This happened with both standard SQL warehouse and serverless SQL warehouse).

Can you verify it, or do you have any thoughts what went wrong?

Thank you a lot.

![image](https://github.com/segmentio/segment-docs/assets/31086329/c4682742-734d-49f0-8368-4f78dff179b5)

**Comment by bigredbug47** [comment]
If the SQL warehouse is running, the process will work normally. (both traditional SQL and serverless SQL)

**Comment by forstisabella** [comment]
Hi @bigredbug47 - Please fill out a support form (https://segment.com/help/contact/) with this information and someone will get in touch!
