### ISSUE TITLE
[Content]:  LaunchDarkly Audiences Destination

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#6482]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-launchdarkly-audiences/#sync-audience

### What part(s) of the article would you like to see updated?

The section under [Sync Audience](https://segment.com/docs/connections/destinations/catalog/actions-launchdarkly-audiences/#sync-audience) should reflect this note on the required fields that don't appear in the mapping.

> Since the **Sync Audience** action is only compatible with Engage traffic, the two required fields `Audience ID` and `Audience Key` will be mapped automatically and do not require configuration within the mappings. This is because Audience ID always defaults to the Engage property : context.personas.computation_id, and Audience Key always defaults to the Engage property : context.personas.computation_key. These fields are intentionally hidden from the app's UI because these values' paths remain static in Engage events, and they're designed to be obfuscated from the mappings in the UI to prevent potential user error.

### Additional information

Discussed in [Slack Thread](https://twilio.slack.com/archives/CC97A542H/p1714514599887099)
[Zendesk Ticket](https://segment.zendesk.com/agent/tickets/542089)

**Comment by forstisabella** [comment]
hi @lizkane222! The docs team autogenerates documentation for mappings, so I can't append anything in that section directly.

We could do one or more of the following options to get this info into the docs: 
1. Open a PR in the action-destination repo to update the description for the mapping
2. Add a note in the Available Actions section of the documentation calling this out ([like in the GA4 web destination](https://segment.com/docs/connections/destinations/catalog/actions-google-analytics-4-web/#available-actions))
3. Add a note in the intro of the doc calling this out

Do you have a feel for which option would be easier for customers to understand?

**Comment by forstisabella** [comment]
Hi @lizkane222 - which of the presented options would be easiest for customers to understand?
