### ISSUE TITLE
[Content]: Request New Page Under Sources

### ISSUE THREAD

**Issue by courtneyga** [segmentio/segment-docs#6614]
### What article on segment.com/docs is affected?

None, new page under "Sources"

### What part(s) of the article would you like to see updated?

# Sending Events via Server Side Libraries

#### Several key factors can prevent events from being successfully ingested into the Segment platform through server-side libraries as sources. Understanding these reasons is crucial for troubleshooting and ensuring data integrity. Here are some suggestions to address these challenges:

1. Payload is too large
There is a maximum of 32KB per normal API request. The batch API endpoint accepts a maximum of 500KB per request, with a limit of 32KB per event in the batch. If you are sending data from a server source, Segment’s API responds with 400 Bad Request if these limits are exceeded.

2. Identifier is not present
Segment's API requires that each payload has a userId and/or anonymousId.

3. Track event is missing name
All Track events to Segment must have an event field.

4. Deduplication
Segment deduplicates based on the messageId field. That field is automatically added to all payloads coming into Segment but if you're setting it yourself, please make sure all events have unique messageId values.

**Comment by forstisabella** [comment]
hi @courtneyga - you mention Segment's API a few times in your original request, is that the tracking API, or a different internal API?

Also, you mention a specific error code for the first item in the list, but not for the other three items. What error codes will users get if they send events without an identifier, or Track events without a name? I assume Segment would silently drop events that have the same messageId, but would that result in an observable error?

**Comment by courtneyga** [comment]
hi @forstisabella , my apologies for being unclear. I am referencing the Segment API's: https://docs.segmentapis.com/

Segment does silently drop the events, and typically the error code is a Bad Request (400).
