### ISSUE TITLE
[Content]: LinkedIn CAPI Add Campaigns to Conversion

### ISSUE THREAD

**Issue by lizkane222** [segmentio/segment-docs#6661]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-linkedin-conversions/#stream-conversion-event

### What part(s) of the article would you like to see updated?

In the [Stream Conversion Event](https://segment.com/docs/connections/destinations/catalog/actions-linkedin-conversions/#stream-conversion-event) table is the field `Add Campaigns to Conversion`. Additional details for this field should be specified within the table's field.

Associating a campaign to a conversion is optional.
If the intended campaigns do not appear in the UI when selecting the value for this field, you can either : 
- manually enter the LinkedIn Rule ID. This Rule ID must already exist and be configured within LinkedIn to be associated with the intended campaigns.
- skip adding this field and Segment will create a new rule that will become visible within the LinkedIn campaign manager, which can then associated with the intended campaigns within LinkedIn.

### Additional information

This was discussed in this [Slack thread](https://twilio.slack.com/archives/CC97A542H/p1716922790235799) and [Zendesk Ticket](https://segment.zendesk.com/agent/tickets/544305).

**Comment by longstoryshort** [comment]
Added this as a tip section to the doc. PR: https://github.com/segmentio/segment-docs/pull/7475
