### ISSUE TITLE
[Content]: Add Information for FB Conversions API Destination

### ISSUE THREAD

**Issue by courtneyga** [segmentio/segment-docs#7247]
### What article on segment.com/docs is affected?

https://segment.com/docs/connections/destinations/catalog/actions-facebook-conversions-api/#custom-event

### What part(s) of the article would you like to see updated?

Add Colorado and Connecticut to this section under, "Custom Event" 
<img width="703" alt="image-20240126-200304" src="https://github.com/user-attachments/assets/33ddbf48-72bf-4a30-aa2e-5cc27001b212">

**Comment by courtneyga** [comment]
Hi there,

It looks like Facebook's documentation
> <https://urldefense.com/v3/__https://developers.facebook.com/docs/marketing-apis/data-processing-options/__;!!NCc8flgU!cM-nPDXReB4VrQ4upoQHqfV-To9ZpJs-_W76KZfeVMMJKN6un1bLfoT4EhqkuPQW7e3ZdEswtTscMZkBVuK1QzY$> includes
> a longer list than California/Colorado/Connecticut - for the Data
> Processing State. Should we add all of the items that are currently
> supported to the Data Processing State description?


Yes, thank you!

**Comment by forstisabella** [comment]
Closing this, as there's nothing I can do here to update the copy, although I have opened a Jira ticket at the request of the stratconn PM to get this on the team's radar.
