### ISSUE TITLE
Hubspot Destination Docs for Group Call need clarification

### ISSUE THREAD

**Issue by AaronAtSegment** [segmentio/segment-docs#889]
### What's wrong? Describe the what you're seeing

The first line in the Group call section of the Hubspot docs says "NOTE: Group calls are not compatible with our Analytics.js library." This sentence is a bit misleading as we believe it means to say that we don't support group for ajs/hubspot/device mode destination (according to reading the rest of the section in the docs), but what about collecting from a.js but sending in cloud-mode to hubspot? If this is possible, the first sentence is misleading and should be clarified to a.js + device mode destination.

### Problem location

https://segment.com/docs/connections/destinations/catalog/hubspot/#group
https://github.com/segmentio/segment-docs/blob/master/src/connections/destinations/catalog/hubspot/index.md

### Suggestions for a fix

Confirm that group is supported by a.js, but only with cloud-mode,  not for device mode, hubspot destination.

**Comment by maracaipe** [comment]
I agree this is confusing; when I read that, I went back to the Group spec page, which makes it implicit that analytics.js DOES have support for group calls.

Then I went here to report and found this issue. I think this should be rephrased to specify the limitation better.
